### ISSUE TITLE
Validation for lists not comprehensive. 

### ISSUE THREAD

**Issue by alairock** [kodemore/gata#15]
You are validating that the type is list, but not that the list contains the right values for more complex cases. 

```python
import typing
from dataclasses import dataclass
from gata import validate_dataclass

@dataclass
class MyTestDC:
    emails: typing.List[typing.Union[str, None]]

def test_json_validation():
    td = {'emails': [123]}
    assert validate_dataclass(MyTestDC(**td)) is None


test_json_validation()
```

This validation passes, though it should fail, since `int` is not one of `str` or `None`.

**Comment by dkraczkowski** [comment]
@alairock Thanks will look into it.

**Comment by dkraczkowski** [comment]
Fixed: https://github.com/kodemore/gata/releases/tag/3.3.1
